{{ $root := . }}
{{ $monitorDefaults := .Values.prometheus.metricProbes }}
{{- range .Values.prometheus.metricProbes.probes }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "azure-metrics-exporter.fullname" $root }}-{{ .name }}
  namespace: {{ template "azure-metrics-exporter.namespace" $root }}
  labels: {{ include "azure-metrics-exporter.labels" $root | indent 4 }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" $monitorDefaults.jobLabel }}
  {{ include "servicemonitor.scrapeLimits" $monitorDefaults | indent 2 }}
  selector:
    matchLabels: {{- include "azure-metrics-exporter.selectorLabels" $root | nindent 6 }}
  endpoints:
    - port: {{ $root.Values.service.portName }}
      scheme: {{ (default .scheme $monitorDefaults.scheme) }}
      path: {{ (default .path $monitorDefaults.path) }}
    {{- with (default .basicAuth $monitorDefaults.basicAuth) }}
      basicAuth: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default .bearerTokenFile $monitorDefaults.bearerTokenFile) }}
      bearerTokenFile: {{ . }}
    {{- end }}
    {{- with (default .tlsConfig $monitorDefaults.tlsConfig) }}
      tlsConfig: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default .proxyUrl $monitorDefaults.proxyUrl) }}
      proxyUrl: {{ . }}
    {{- end }}
    {{- with (default .interval $monitorDefaults.interval) }}
      interval: {{ . }}
    {{- end }}
    {{- with (default .scrapeTimeout $monitorDefaults.scrapeTimeout) }}
      scrapeTimeout: {{ . }}
    {{- end }}
    {{- with (default .relabelings $monitorDefaults.relabelings) }}
      relabelings: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default .metricRelabelings $monitorDefaults.metricRelabelings) }}
      metricRelabelings: {{- toYaml . | nindent 8 }}
    {{- end }}
      params:
        {{- with (merge .params $monitorDefaults.params) }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
